sudo: required
dist: trusty
language: generic

branches:
  except:
   - gh-pages

env:
  # This will check any ROS distro supported on this OS
  # checking devel and install separately so that they don't influence each other (dependencies, path, env, etc.)
  - CI_ROS_DISTRO=indigo ROS_FLOW=devel
  - CI_ROS_DISTRO=indigo ROS_FLOW=install
  - CI_ROS_DISTRO=jade ROS_FLOW=devel
  - CI_ROS_DISTRO=jade ROS_FLOW=install
  # TODO : test all possible flows (installing deps on devel or not, etc.)

install:
# Add ROS repositories
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
# Install ROS base
  - sudo apt-get install ros-$CI_ROS_DISTRO-ros-base -y
# Install and initialize rosdep
  - sudo apt-get install python-rosdep -y
  - sudo `which rosdep` init
  - rosdep update
# Use rosdep to install dependencies
  - rosdep install --default-yes --from-paths ./ --rosdistro $CI_ROS_DISTRO

# full ROS setup, build and test
script:
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash && rospack profile
  - ./travis_checks.sh

notifications:
  email: false

